### ISSUE TITLE
Error occurred when trying to connect with the email server

### ISSUE THREAD

**Issue by andreakys** [fengoffice/fengoffice#22]
Help wanted

Hello,
I installed  Feng Office 3.7.0.5 on a local server in my office
Apache/2.4.39 (Win64) PHP/7.1.30

I can not properly configure the mail.

Error found:
Error occurred when trying to connect with the email server.
Mail server response:
Generic login error

This in the Log file:

Session "default" started at 2019-07-17T19:30:01+0000
#1 ERROR: Error: fsockopen(): unable to connect to ssl://pop3.visualtronics.com:995 (Unable to find the socket transport &quot;ssl&quot; - did you forget to enable it when you configured PHP?) in 'C:\Server\data\htdocs\feng\library\PEAR\Net\Socket.php' on line 226 (error code: 2)
#2 DEBUG: ERROR CHECKING ACCOUNT CONNECTION:
    Generic login error
Time since start: 0.068810939788818 seconds

I enabled the extension on the server:
extension=php_openssl.dll

I think it might be a problem with the certificate ssl
There is a detailed guide for how to install the ssl certificate in my local server?

Same problem with Gmail accounts:

Session "default" started at 2019-07-17T20:05:50+0000
#1 FATAL: Error: Call to undefined function str_sstr_starts_with() in C:\Server\data\htdocs\feng\library\PEAR\Net\Socket.php:198
    Stack trace:
    #0 C:\Server\data\htdocs\feng\library\PEAR\Net\IMAPProtocol.php(189): Net_Socket->connect('ssl://imap.gmai...', 993, NULL, '60', Array)
    #1 C:\Server\data\htdocs\feng\library\PEAR\Net\IMAP.php(70): Net_IMAPProtocol->cmdConnect('ssl://imap.gmai...', 993)
    #2 C:\Server\data\htdocs\feng\library\PEAR\Net\IMAP.php(48): Net_IMAP->connect('ssl://imap.gmai...', 993, NULL)
    #3 C:\Server\data\htdocs\feng\plugins\mail\application\models\mail_accounts\MailAccount.class.php(371): Net_IMAP->Net_IMAP(NULL, 'ssl://imap.gmai...', 993, NULL, Array)
    #4 C:\Server\data\htdocs\feng\plugins\mail\application\controllers\MailController.class.php(3434): MailAccount->imapConnect()
    #5 C:\Server\data\htdocs\feng\environment\classes\controller\Controller.class.php(76): MailController->check_mail_account_connection()
    #6 C:\Server\data\htdocs\feng\environment\classes\controller\PageController.class.php(62): Controller->execute('check_mail_acco...')
    #7 C:\Server\data\htdocs\feng\environment\classes\Env.class.php(133): PageController->execute('check_mail_acco...')
    #8 C:\Server\data\htdocs\feng\init.php(177): Env::executeAction('mail', 'check_mail_acco...')
    #9 C:\Server\data\htdocs\feng\index.php(7): require('C:\\Server\\data\\...')
    #10 {main}
Time since start: 0.065261125564575 seconds

**Comment by peternagelsa** [comment]
I am also experiencing issues with connecting to the email server. My setup is as follows:

Feng Office Version 3.7.2.16
PHP Version 7.2.7
Database Server: Type (MariaDB), version (10.2.25-MariaDB - MariaDB Server). 

In my case, it is as if connection with the server is not made at all, but if it does connect the information retrieved from the server is not displayed, the screen below icons is blank, and with screen refresh, the email option bar reappears.

**Comment by Marzal** [comment]
This was a Typo in file `Socket.php` line 198, `function str_sstr_starts_with` was not the correct function. But it's fixed in new releases.

IMO this issue can be closed.
