### ISSUE TITLE
Upgrade difficulties (Feng Office 2.5.1.4 -> 3.7.2.16)

### ISSUE THREAD

**Issue by marjwyatt** [fengoffice/fengoffice#35]
I apologize, in advance, for this lengthy post.  I've tried to supply all the information that I've got but, if you need something more, feel free to ask.

Problem Statement:
I've spent the last couple days testing the upgrade from version 2.5.14 to one that supports PHP 7.x.  Through research, I learned that this version (3.7.2.16) supported PHP 7.1 and above.  I do not have PHP 7.1 installed on my VPS because it is reaching EOL at the end of 2020 but I do have both PHP 7.2 and PHP 7.3 installed.

After several failed attempts to upgrade, I tried an experiment and learned that I am able to do a clean install of Feng Office 3.7.2.16 on a subdomain running PHP 7.2.33.  That suggests that my PHP 7.2.33 installation is configured with all the extensions necessary to run the application.  But, it does not bring in the client and project history that I've maintained since 2013 when I began to use Feng Office. 

Here's the process that I used to update:
1) Verified that copy of installation worked.
2) Modified config.php  to access PHP 7.x as described in the documentation (i.e., define('DB_ADAPTER', 'mysqli'); )
3) Using MultiPHP on CPanel, changed versions from 5.6 to inherited, which is PHP 7.2.33.
3) Uploaded a zip file of Feng Office 3.7.2.16 do the subdomain and unpacked it.
4) Using CPanel file manager, copied all folders from the unpacked zip into the previously tested and functional location.
5) Verified folder permissions are correct (upload, config, cache and tmp folders with 775 or 777 permissions).
6) Using the CPanel terminal console, ran this command:
    php FENG_ROOT/public/upgrade/console.php

Here's the output from the terminal console:
`Config file found and loaded.
File '/config/config.php' exists and is writable
Folder '/config' exists and is writable
Folder '/cache' exists and is writable
Folder '/tmp' exists and is writable
Folder '/upload' exists and is writable
Error: Extension 'mysql' is not loaded
2020-08-25 23:46:42 - Updating plugins...
2020-08-25 23:46:43 - Finished plugins update.
vmnet@virtuallymarj.net [~/public_html/fengupgrade]# pwd
/home/vmnet/public_html/fengupgrade
vmnet@virtuallymarj.net [~/public_html/fengupgrade]# cd ..install
jailshell: cd: ..install: No such file or directory
vmnet@virtuallymarj.net [~/public_html/fengupgrade]# cd ..
vmnet@virtuallymarj.net [~/public_html]# pwd
/home/vmnet/public_html
vmnet@virtuallymarj.net [~/public_html]# cd fengupgrade
vmnet@virtuallymarj.net [~/public_html/fengupgrade]# php public/install/plugin-console.php list
vmnet@virtuallymarj.net [~/public_html/fengupgrade]# php public/install/plugin-console.php update_all
vmnet@virtuallymarj.net [~/public_html/fengupgrade]#`

I had seen the Error "Extension 'mysql' is not loaded" when using the browser upgrade before and had researched it.  From a link on stackoverflow, I found this advice, "php-mysql has been deprecated years ago and PHP developers has warned that the extension was going to be removed on PHP 7 for years now. It is recommended to use php-mysqli instead."  I have verified that the mysqli extension is enabled.  The relevant ini file is /opt/cpanel/ea-php72/root/etc/php.d/30-mysqli.ini and all that it contains is these lines of code: 
`; Enable mysqli extension module
extension=mysqli.so` 

These are errors logged in cache/log.php yesterday:
`-------------------------------------------------------------------------------

Session "default" started at 2020-08-25T23:46:42+0000
#1 FATAL: DBQueryError: Query failed with message 'Unknown column 'timezone_id' in 'field list'' in /home/vmnet/public_html/fengupgrade/environment/library/database/adapters/AbstractDBAdapter.class.php:395
    Stack trace:
    #0 /home/vmnet/public_html/fengupgrade/environment/library/database/adapters/AbstractDBAdapter.class.php(291): AbstractDBAdapter->prepareAndExecute('\r\n      \t\tSELEC...', NULL)
    #1 /home/vmnet/public_html/fengupgrade/environment/library/database/DB.class.php(189): AbstractDBAdapter->executeOne('\r\n      \t\tSELEC...', NULL)
    #2 /home/vmnet/public_html/fengupgrade/application/models/ContentDataObjects.class.php(343): DB::executeOne('\r\n      \t\tSELEC...')
    #3 /home/vmnet/public_html/fengupgrade/environment/classes/dataaccess/DataManager.class.php(455): ContentDataObjects->loadRow(2)
    #4 /home/vmnet/public_html/fengupgrade/environment/classes/dataaccess/DataManager.class.php(359): DataManager->load(2, false)
    #5 /home/vmnet/public_html/fengupgrade/application/models/ContentDataObjects.class.php(367): DataManager->findById(2, false)
    #6 /home/vmnet/public_html/fengupgrade/application/models/contacts/base/BaseContacts.class.php(226): ContentDataObjects->findById(2, false)
    #7 /home/vmnet/public_html/fengupgrade/application/models/contacts/base/BaseContacts.class.php(228): BaseContacts->findById(2, false)
    #8 /home/vmnet/public_html/fengupgrade/application/models/ContentDataObject.class.php(248): BaseContacts::findById(2)
    #9 /home/vmnet/public_html/fengupgrade/application/models/CompanyWebsite.class.php(73): ContentDataObject->getCreatedBy()
    #10 /home/vmnet/public_html/fengupgrade/application/models/CompanyWebsite.class.php(46): CompanyWebsite->initCompany()
    #11 /home/vmnet/public_html/fengupgrade/application/models/CompanyWebsite.class.php(50): CompanyWebsite->init()
    #12 /home/vmnet/public_html/fengupgrade/application/application.php(19): CompanyWebsite::init()
    #13 /home/vmnet/public_html/fengupgrade/init.php(159): require_once('/home/vmnet/pub...')
    #14 /home/vmnet/public_html/fengupgrade/public/install/plugin-console.php(8): require_once('/home/vmnet/pub...')
    #15 {main}
Time since start: 0.23765516281128 seconds
-------------------------------------------------------------------------------

Session "default" started at 2020-08-25T23:50:07+0000
#1 FATAL: DBQueryError: Query failed with message 'Unknown column 'timezone_id' in 'field list'' in /home/vmnet/public_html/fengupgrade/environment/library/database/adapters/AbstractDBAdapter.class.php:395
    Stack trace:
    #0 /home/vmnet/public_html/fengupgrade/environment/library/database/adapters/AbstractDBAdapter.class.php(291): AbstractDBAdapter->prepareAndExecute('\r\n      \t\tSELEC...', NULL)
    #1 /home/vmnet/public_html/fengupgrade/environment/library/database/DB.class.php(189): AbstractDBAdapter->executeOne('\r\n      \t\tSELEC...', NULL)
    #2 /home/vmnet/public_html/fengupgrade/application/models/ContentDataObjects.class.php(343): DB::executeOne('\r\n      \t\tSELEC...')
    #3 /home/vmnet/public_html/fengupgrade/environment/classes/dataaccess/DataManager.class.php(455): ContentDataObjects->loadRow(2)
    #4 /home/vmnet/public_html/fengupgrade/environment/classes/dataaccess/DataManager.class.php(359): DataManager->load(2, false)
    #5 /home/vmnet/public_html/fengupgrade/application/models/ContentDataObjects.class.php(367): DataManager->findById(2, false)
    #6 /home/vmnet/public_html/fengupgrade/application/models/contacts/base/BaseContacts.class.php(226): ContentDataObjects->findById(2, false)
    #7 /home/vmnet/public_html/fengupgrade/application/models/contacts/base/BaseContacts.class.php(228): BaseContacts->findById(2, false)
    #8 /home/vmnet/public_html/fengupgrade/application/models/ContentDataObject.class.php(248): BaseContacts::findById(2)
    #9 /home/vmnet/public_html/fengupgrade/application/models/CompanyWebsite.class.php(73): ContentDataObject->getCreatedBy()
    #10 /home/vmnet/public_html/fengupgrade/application/models/CompanyWebsite.class.php(46): CompanyWebsite->initCompany()
    #11 /home/vmnet/public_html/fengupgrade/application/models/CompanyWebsite.class.php(50): CompanyWebsite->init()
    #12 /home/vmnet/public_html/fengupgrade/application/application.php(19): CompanyWebsite::init()
    #13 /home/vmnet/public_html/fengupgrade/init.php(159): require_once('/home/vmnet/pub...')
    #14 /home/vmnet/public_html/fengupgrade/public/install/plugin-console.php(8): require_once('/home/vmnet/pub...')
    #15 {main}
Time since start: 0.27195906639099 seconds
-------------------------------------------------------------------------------

Session "default" started at 2020-08-25T23:50:35+0000
#1 FATAL: DBQueryError: Query failed with message 'Unknown column 'timezone_id' in 'field list'' in /home/vmnet/public_html/fengupgrade/environment/library/database/adapters/AbstractDBAdapter.class.php:395
    Stack trace:
    #0 /home/vmnet/public_html/fengupgrade/environment/library/database/adapters/AbstractDBAdapter.class.php(291): AbstractDBAdapter->prepareAndExecute('\r\n      \t\tSELEC...', NULL)
    #1 /home/vmnet/public_html/fengupgrade/environment/library/database/DB.class.php(189): AbstractDBAdapter->executeOne('\r\n      \t\tSELEC...', NULL)
    #2 /home/vmnet/public_html/fengupgrade/application/models/ContentDataObjects.class.php(343): DB::executeOne('\r\n      \t\tSELEC...')
    #3 /home/vmnet/public_html/fengupgrade/environment/classes/dataaccess/DataManager.class.php(455): ContentDataObjects->loadRow(2)
    #4 /home/vmnet/public_html/fengupgrade/environment/classes/dataaccess/DataManager.class.php(359): DataManager->load(2, false)
    #5 /home/vmnet/public_html/fengupgrade/application/models/ContentDataObjects.class.php(367): DataManager->findById(2, false)
    #6 /home/vmnet/public_html/fengupgrade/application/models/contacts/base/BaseContacts.class.php(226): ContentDataObjects->findById(2, false)
    #7 /home/vmnet/public_html/fengupgrade/application/models/contacts/base/BaseContacts.class.php(228): BaseContacts->findById(2, false)
    #8 /home/vmnet/public_html/fengupgrade/application/models/ContentDataObject.class.php(248): BaseContacts::findById(2)
    #9 /home/vmnet/public_html/fengupgrade/application/models/CompanyWebsite.class.php(73): ContentDataObject->getCreatedBy()
    #10 /home/vmnet/public_html/fengupgrade/application/models/CompanyWebsite.class.php(46): CompanyWebsite->initCompany()
    #11 /home/vmnet/public_html/fengupgrade/application/models/CompanyWebsite.class.php(50): CompanyWebsite->init()
    #12 /home/vmnet/public_html/fengupgrade/application/application.php(19): CompanyWebsite::init()
    #13 /home/vmnet/public_html/fengupgrade/init.php(159): require_once('/home/vmnet/pub...')
    #14 /home/vmnet/public_html/fengupgrade/public/install/plugin-console.php(8): require_once('/home/vmnet/pub...')
    #15 {main}
Time since start: 0.16601586341858 seconds
-------------------------------------------------------------------------------

Session "default" started at 2020-08-25T23:51:32+0000
#1 FATAL: DBQueryError: Query failed with message 'Unknown column 'timezone_id' in 'field list'' in /home/vmnet/public_html/fengupgrade/environment/library/database/adapters/AbstractDBAdapter.class.php:395
    Stack trace:
    #0 /home/vmnet/public_html/fengupgrade/environment/library/database/adapters/AbstractDBAdapter.class.php(291): AbstractDBAdapter->prepareAndExecute('\r\n      \t\tSELEC...', NULL)
    #1 /home/vmnet/public_html/fengupgrade/environment/library/database/DB.class.php(189): AbstractDBAdapter->executeOne('\r\n      \t\tSELEC...', NULL)
    #2 /home/vmnet/public_html/fengupgrade/application/models/ContentDataObjects.class.php(343): DB::executeOne('\r\n      \t\tSELEC...')
    #3 /home/vmnet/public_html/fengupgrade/environment/classes/dataaccess/DataManager.class.php(455): ContentDataObjects->loadRow(2)
    #4 /home/vmnet/public_html/fengupgrade/environment/classes/dataaccess/DataManager.class.php(359): DataManager->load(2, false)
    #5 /home/vmnet/public_html/fengupgrade/application/models/ContentDataObjects.class.php(367): DataManager->findById(2, false)
    #6 /home/vmnet/public_html/fengupgrade/application/models/contacts/base/BaseContacts.class.php(226): ContentDataObjects->findById(2, false)
    #7 /home/vmnet/public_html/fengupgrade/application/models/contacts/base/BaseContacts.class.php(228): BaseContacts->findById(2, false)
    #8 /home/vmnet/public_html/fengupgrade/application/models/ContentDataObject.class.php(248): BaseContacts::findById(2)
    #9 /home/vmnet/public_html/fengupgrade/application/models/CompanyWebsite.class.php(73): ContentDataObject->getCreatedBy()
    #10 /home/vmnet/public_html/fengupgrade/application/models/CompanyWebsite.class.php(46): CompanyWebsite->initCompany()
    #11 /home/vmnet/public_html/fengupgrade/application/models/CompanyWebsite.class.php(50): CompanyWebsite->init()
    #12 /home/vmnet/public_html/fengupgrade/application/application.php(19): CompanyWebsite::init()
    #13 /home/vmnet/public_html/fengupgrade/init.php(159): require_once('/home/vmnet/pub...')
    #14 /home/vmnet/public_html/fengupgrade/index.php(7): require('/home/vmnet/pub...')
    #15 {main}
Time since start: 0.059790849685669 seconds
-------------------------------------------------------------------------------

Session "default" started at 2020-08-25T23:51:53+0000
#1 FATAL: DBQueryError: Query failed with message 'Unknown column 'timezone_id' in 'field list'' in /home/vmnet/public_html/fengupgrade/environment/library/database/adapters/AbstractDBAdapter.class.php:395
    Stack trace:
    #0 /home/vmnet/public_html/fengupgrade/environment/library/database/adapters/AbstractDBAdapter.class.php(291): AbstractDBAdapter->prepareAndExecute('\r\n      \t\tSELEC...', NULL)
    #1 /home/vmnet/public_html/fengupgrade/environment/library/database/DB.class.php(189): AbstractDBAdapter->executeOne('\r\n      \t\tSELEC...', NULL)
    #2 /home/vmnet/public_html/fengupgrade/application/models/ContentDataObjects.class.php(343): DB::executeOne('\r\n      \t\tSELEC...')
    #3 /home/vmnet/public_html/fengupgrade/environment/classes/dataaccess/DataManager.class.php(455): ContentDataObjects->loadRow(2)
    #4 /home/vmnet/public_html/fengupgrade/environment/classes/dataaccess/DataManager.class.php(359): DataManager->load(2, false)
    #5 /home/vmnet/public_html/fengupgrade/application/models/ContentDataObjects.class.php(367): DataManager->findById(2, false)
    #6 /home/vmnet/public_html/fengupgrade/application/models/contacts/base/BaseContacts.class.php(226): ContentDataObjects->findById(2, false)
    #7 /home/vmnet/public_html/fengupgrade/application/models/contacts/base/BaseContacts.class.php(228): BaseContacts->findById(2, false)
    #8 /home/vmnet/public_html/fengupgrade/application/models/ContentDataObject.class.php(248): BaseContacts::findById(2)
    #9 /home/vmnet/public_html/fengupgrade/application/models/CompanyWebsite.class.php(73): ContentDataObject->getCreatedBy()
    #10 /home/vmnet/public_html/fengupgrade/application/models/CompanyWebsite.class.php(46): CompanyWebsite->initCompany()
    #11 /home/vmnet/public_html/fengupgrade/application/models/CompanyWebsite.class.php(50): CompanyWebsite->init()
    #12 /home/vmnet/public_html/fengupgrade/application/application.php(19): CompanyWebsite::init()
    #13 /home/vmnet/public_html/fengupgrade/init.php(159): require_once('/home/vmnet/pub...')
    #14 /home/vmnet/public_html/fengupgrade/index.php(7): require('/home/vmnet/pub...')
    #15 {main}
Time since start: 0.057355880737305 seconds
-------------------------------------------------------------------------------

Session "default" started at 2020-08-25T23:53:53+0000
#1 FATAL: DBQueryError: Query failed with message 'Unknown column 'timezone_id' in 'field list'' in /home/vmnet/public_html/fengupgrade/environment/library/database/adapters/AbstractDBAdapter.class.php:395
    Stack trace:
    #0 /home/vmnet/public_html/fengupgrade/environment/library/database/adapters/AbstractDBAdapter.class.php(291): AbstractDBAdapter->prepareAndExecute('\r\n      \t\tSELEC...', NULL)
    #1 /home/vmnet/public_html/fengupgrade/environment/library/database/DB.class.php(189): AbstractDBAdapter->executeOne('\r\n      \t\tSELEC...', NULL)
    #2 /home/vmnet/public_html/fengupgrade/application/models/ContentDataObjects.class.php(343): DB::executeOne('\r\n      \t\tSELEC...')
    #3 /home/vmnet/public_html/fengupgrade/environment/classes/dataaccess/DataManager.class.php(455): ContentDataObjects->loadRow(2)
    #4 /home/vmnet/public_html/fengupgrade/environment/classes/dataaccess/DataManager.class.php(359): DataManager->load(2, false)
    #5 /home/vmnet/public_html/fengupgrade/application/models/ContentDataObjects.class.php(367): DataManager->findById(2, false)
    #6 /home/vmnet/public_html/fengupgrade/application/models/contacts/base/BaseContacts.class.php(226): ContentDataObjects->findById(2, false)
    #7 /home/vmnet/public_html/fengupgrade/application/models/contacts/base/BaseContacts.class.php(228): BaseContacts->findById(2, false)
    #8 /home/vmnet/public_html/fengupgrade/application/models/ContentDataObject.class.php(248): BaseContacts::findById(2)
    #9 /home/vmnet/public_html/fengupgrade/application/models/CompanyWebsite.class.php(73): ContentDataObject->getCreatedBy()
    #10 /home/vmnet/public_html/fengupgrade/application/models/CompanyWebsite.class.php(46): CompanyWebsite->initCompany()
    #11 /home/vmnet/public_html/fengupgrade/application/models/CompanyWebsite.class.php(50): CompanyWebsite->init()
    #12 /home/vmnet/public_html/fengupgrade/application/application.php(19): CompanyWebsite::init()
    #13 /home/vmnet/public_html/fengupgrade/init.php(159): require_once('/home/vmnet/pub...')
    #14 /home/vmnet/public_html/fengupgrade/index.php(7): require('/home/vmnet/pub...')
    #15 {main}
Time since start: 0.058996200561523 seconds
-------------------------------------------------------------------------------

Session "default" started at 2020-08-25T23:54:06+0000
#1 FATAL: DBQueryError: Query failed with message 'Unknown column 'timezone_id' in 'field list'' in /home/vmnet/public_html/fengupgrade/environment/library/database/adapters/AbstractDBAdapter.class.php:395
    Stack trace:
    #0 /home/vmnet/public_html/fengupgrade/environment/library/database/adapters/AbstractDBAdapter.class.php(291): AbstractDBAdapter->prepareAndExecute('\r\n      \t\tSELEC...', NULL)
    #1 /home/vmnet/public_html/fengupgrade/environment/library/database/DB.class.php(189): AbstractDBAdapter->executeOne('\r\n      \t\tSELEC...', NULL)
    #2 /home/vmnet/public_html/fengupgrade/application/models/ContentDataObjects.class.php(343): DB::executeOne('\r\n      \t\tSELEC...')
    #3 /home/vmnet/public_html/fengupgrade/environment/classes/dataaccess/DataManager.class.php(455): ContentDataObjects->loadRow(2)
    #4 /home/vmnet/public_html/fengupgrade/environment/classes/dataaccess/DataManager.class.php(359): DataManager->load(2, false)
    #5 /home/vmnet/public_html/fengupgrade/application/models/ContentDataObjects.class.php(367): DataManager->findById(2, false)
    #6 /home/vmnet/public_html/fengupgrade/application/models/contacts/base/BaseContacts.class.php(226): ContentDataObjects->findById(2, false)
    #7 /home/vmnet/public_html/fengupgrade/application/models/contacts/base/BaseContacts.class.php(228): BaseContacts->findById(2, false)
    #8 /home/vmnet/public_html/fengupgrade/application/models/ContentDataObject.class.php(248): BaseContacts::findById(2)
    #9 /home/vmnet/public_html/fengupgrade/application/models/CompanyWebsite.class.php(73): ContentDataObject->getCreatedBy()
    #10 /home/vmnet/public_html/fengupgrade/application/models/CompanyWebsite.class.php(46): CompanyWebsite->initCompany()
    #11 /home/vmnet/public_html/fengupgrade/application/models/CompanyWebsite.class.php(50): CompanyWebsite->init()
    #12 /home/vmnet/public_html/fengupgrade/application/application.php(19): CompanyWebsite::init()
    #13 /home/vmnet/public_html/fengupgrade/init.php(159): require_once('/home/vmnet/pub...')
    #14 /home/vmnet/public_html/fengupgrade/index.php(7): require('/home/vmnet/pub...')
    #15 {main}
Time since start: 0.061240911483765 seconds
-------------------------------------------------------------------------------

Session "default" started at 2020-08-25T23:58:24+0000
#1 FATAL: DBQueryError: Query failed with message 'Unknown column 'timezone_id' in 'field list'' in /home/vmnet/public_html/fengupgrade/environment/library/database/adapters/AbstractDBAdapter.class.php:395
    Stack trace:
    #0 /home/vmnet/public_html/fengupgrade/environment/library/database/adapters/AbstractDBAdapter.class.php(291): AbstractDBAdapter->prepareAndExecute('\r\n      \t\tSELEC...', NULL)
    #1 /home/vmnet/public_html/fengupgrade/environment/library/database/DB.class.php(189): AbstractDBAdapter->executeOne('\r\n      \t\tSELEC...', NULL)
    #2 /home/vmnet/public_html/fengupgrade/application/models/ContentDataObjects.class.php(343): DB::executeOne('\r\n      \t\tSELEC...')
    #3 /home/vmnet/public_html/fengupgrade/environment/classes/dataaccess/DataManager.class.php(455): ContentDataObjects->loadRow(2)
    #4 /home/vmnet/public_html/fengupgrade/environment/classes/dataaccess/DataManager.class.php(359): DataManager->load(2, false)
    #5 /home/vmnet/public_html/fengupgrade/application/models/ContentDataObjects.class.php(367): DataManager->findById(2, false)
    #6 /home/vmnet/public_html/fengupgrade/application/models/contacts/base/BaseContacts.class.php(226): ContentDataObjects->findById(2, false)
    #7 /home/vmnet/public_html/fengupgrade/application/models/contacts/base/BaseContacts.class.php(228): BaseContacts->findById(2, false)
    #8 /home/vmnet/public_html/fengupgrade/application/models/ContentDataObject.class.php(248): BaseContacts::findById(2)
    #9 /home/vmnet/public_html/fengupgrade/application/models/CompanyWebsite.class.php(73): ContentDataObject->getCreatedBy()
    #10 /home/vmnet/public_html/fengupgrade/application/models/CompanyWebsite.class.php(46): CompanyWebsite->initCompany()
    #11 /home/vmnet/public_html/fengupgrade/application/models/CompanyWebsite.class.php(50): CompanyWebsite->init()
    #12 /home/vmnet/public_html/fengupgrade/application/application.php(19): CompanyWebsite::init()
    #13 /home/vmnet/public_html/fengupgrade/init.php(159): require_once('/home/vmnet/pub...')
    #14 /home/vmnet/public_html/fengupgrade/index.php(7): require('/home/vmnet/pub...')
    #15 {main}
Time since start: 0.058409929275513 seconds
-------------------------------------------------------------------------------
`
Here are the contents of my config.php lacking db usernames, passwords, etc.
`<?php
  define('DB_ADAPTER', 'mysqli');
  define('DB_HOST', 'localhost');
  define('DB_USER', 'PRIVATE-INFO');
  define('DB_PASS', 'PRIVATE-INFO');
  define('DB_NAME', 'PRIVATE-INFO');
  define('DB_PERSIST', true);
  define('TABLE_PREFIX', 'cL1entZ_');
  define('DB_ENGINE', 'InnoDB');
  define('ROOT_URL', 'https://fengupgrade.virtuallymarj.net');
  define('DEFAULT_LOCALIZATION', 'en_us');
  define('COOKIE_PATH', '/');
  define('DEBUG', true);
  define('SEED', '49799ecee83f6396ba8cc68da2b763b6');
  define('DB_CHARSET', 'utf8');
  return true;
  ?>`

Here's what I've been wondering.  Sometimes, when a client has allowed their WordPress installations to fall too far behind, I have had to "step through" upgrades to make their sites compatible for one-click upgrades.  Does that apply here?  Do I have to "step through" previous versions of Feng Office to prepare it for the leap forward?

If not, can you provide any guidance on how I can solve this upgrade problem?

**Comment by marjwyatt** [comment]
I reverted PHP version to 5.6 and got past the blank white screen.  This is the information  shown on the page:

--------------------------

Query failed with message 'Unknown column 'timezone_id' in 'field list''
--
Error params:
File: | /home/vmnet/public_html/fengupgrade/environment/library/database/adapters/AbstractDBAdapter.class.php
Line: | 395
Sql: | SELECT `id`, `object_type_id`, `name`, `created_on`,  `created_by_id`, `updated_on`, `updated_by_id`, `trashed_on`,  `trashed_by_id`, `archived_on`, `archived_by_id`, `timezone_id`,  `timezone_value`, `object_id`, `first_name`, `surname`, `is_company`,  `company_id`, `department`, `job_title`, `birthday`, `timezone`,  `user_type`, `is_active_user`, `token`, `salt`, `twister`,  `display_name`, `permission_group_id`, `username`,  `contact_passwords_id`, `picture_file`, `picture_file_small`,  `picture_file_medium`, `avatar_file`, `comments`, `last_login`,  `last_activity`, `last_visit`, `personal_member_id`, `disabled`,  `token_disabled`, `default_billing_id`, `user_timezone_id`        		FROM `cL1entZ_contacts`	INNER JOIN `cL1entZ_objects` o       		ON o.id = `cL1entZ_contacts`.object_id        		WHERE `object_id` = '2'
Error number: | 1054
Error message: | Unknown column 'timezone_id' in 'field list'
Backtrace:
#0  /home/vmnet/public_html/fengupgrade/environment/library/database/adapters/AbstractDBAdapter.class.php(291):  AbstractDBAdapter->prepareAndExecute('\r\n      \t\tSELEC...', NULL) #1  /home/vmnet/public_html/fengupgrade/environment/library/database/DB.class.php(189):  AbstractDBAdapter->executeOne('\r\n      \t\tSELEC...', NULL) #2  /home/vmnet/public_html/fengupgrade/application/models/ContentDataObjects.class.php(343):  DB::executeOne('\r\n      \t\tSELEC...') #3  /home/vmnet/public_html/fengupgrade/environment/classes/dataaccess/DataManager.class.php(455):  ContentDataObjects->loadRow(2) #4 /home/vmnet/public_html/fengupgrade/environment/classes/dataaccess/DataManager.class.php(359): DataManager->load(2, false) #5 /home/vmnet/public_html/fengupgrade/application/models/ContentDataObjects.class.php(367): DataManager->findById(2, false) #6  /home/vmnet/public_html/fengupgrade/application/models/contacts/base/BaseContacts.class.php(226):  ContentDataObjects->findById(2, false) #7  /home/vmnet/public_html/fengupgrade/application/models/contacts/base/BaseContacts.class.php(228):  BaseContacts->findById(2, false) #8 /home/vmnet/public_html/fengupgrade/application/models/ContentDataObject.class.php(248): BaseContacts->findById(2) #9 /home/vmnet/public_html/fengupgrade/application/models/CompanyWebsite.class.php(73): ContentDataObject->getCreatedBy() #10 /home/vmnet/public_html/fengupgrade/application/models/CompanyWebsite.class.php(46): CompanyWebsite->initCompany() #11 /home/vmnet/public_html/fengupgrade/application/models/CompanyWebsite.class.php(50): CompanyWebsite->init() #12 /home/vmnet/public_html/fengupgrade/application/application.php(19): CompanyWebsite::init() #13 /home/vmnet/public_html/fengupgrade/init.php(159): require_once('/home/vmnet/pub...') #14 /home/vmnet/public_html/fengupgrade/index.php(7): require('/home/vmnet/pub...') #15 {main}
Autoglobal varibles:
$_GET: | Array (   ['c'] => (string) 'access'   ['a'] => (string) 'login' )
$_POST: |  
$_COOKIE: |  
$_SESSION: |  
Execution time:
Total execution time: 0.209340 seconds
---------------------------

I have verified that there is no 'timezone_id' column in the table.  When was this column added?  

Here's the code surrounding line 395, which is throwing the error:
```
/**
    * Prepare SQL and execute it...
    *
    * @access protected
    * @param string $sql
    * @return DBResult
    * @throws DBQueryError
    */
    protected function prepareAndExecute($sql, $arguments = null) {
      if(is_array($arguments)) $sql = DB::prepareString($sql, $arguments);
      
      $query_result = $this->executeQuery($sql, $this->link);
      DB::addToSQLLog($sql);
      
      if($query_result === false) {
        throw new DBQueryError($sql, $this->lastErrorCode(), $this->lastError());
      } // if
      return $query_result === true ? true : new DBResult($this, $query_result);
      
    } // prepareAndExecute
```

Where is this SQL query prepared and can it be altered?

Or, from my previous post, was the structure of the contacts table changed in a previous version?

PHP 5.6 is reaching EOL.  I need to get this problem solved or I won't receive cPanel updates because I'm running an obsolete version of PHP.
