### ISSUE TITLE
3.10.7.8 Installation problem on step 4. mysqli_sql_exception 

### ISSUE THREAD

**Issue by savchenkolex** [fengoffice/fengoffice#89]
Hi, there

I try install new relize 3.10.7.8 on ubuntu-server and get error on 4 step. So can`t finish installation process.
PHP version: PHP 8.1.2-1ubuntu2.14 (cli) (built: Aug 18 2023 11:41:11) (NTS)

In browser got next message: 

```
Database connection has been established successfully InnoDB storage engine is supported Tables created in 'fengoffice'. (Executed queries: 114) Initial data imported into 'fengoffice'. (Executed queries: 51) /home/ubuntu/.../fengoffice/plugins/core_dimensions/info.php Schema created for plugin core_dimensions
```
And apache error log:

```
PHP Fatal error:  Uncaught mysqli_sql_exception: Field 'description' doesn't have a default value in /home/ubuntu/.../public/install/installation/acInstallation.class.php:349\nStack trace:\n#0 /home/ubuntu/.../fengoffice/public/install/installation/acInstallation.class.php(349): mysqli_query()\n#1 /home/ubuntu/.../fengoffice/public/install/installation/acInstallation.class.php(714): acInstallation->executeMultipleQueries()\n#2 /home/ubuntu/.../fengoffice/public/install/installation/acInstallation.class.php(218): acInstallation->installPlugins()\n#3 /home/ubuntu/.../fengoffice/public/install/installation/steps/FinishStep.class.php(56): acInstallation->execute()\n#4 /home/ubuntu/.../fengoffice/public/install/library/classes/ScriptInstaller.class.php(93): FinishStep->execute()\n#5 /home/ubuntu/.../fengoffice/public/install/index.php(11): ScriptInstaller->executeStep()\n#6 {main}\n  thrown in /home/ubuntu/.../fengoffice/public/install/installation/acInstallation.class.php on line 349, referer: https://.../fengoffice/public/install/index.php?step=3
```

What can I do for fix this?

**Comment by SantiFeng** [comment]
Hello @savchenkolex.

Thank you for submitting this issue. Please provide your MySQL version. Tested this today in MySQL 8.0.35 and it works correctly.

Also notice that version 3.10.7.9 has been released.

Let us know if you have more troubles.

**Comment by savchenkolex** [comment]
Hi, @SantiFeng 
I checked. It's almost MySQL

```bash
sudo mysql --version
mysql  Ver 15.1 Distrib 10.6.12-MariaDB, for debian-linux-gnu (x86_64)
```
I also tried installing the latest release (3.10.8.1) and got the same error. 
In browser (installation step=4)
`Database connection has been established successfully InnoDB storage engine is supported Tables created in 'fengoffice'. (Executed queries: 114) Initial data imported into 'fengoffice'. (Executed queries: 51) /home/ubuntu/.../fengoffice/plugins/core_dimensions/info.php Schema created for plugin core_dimensions`
and blank page.

In /var/log/apache2/error.log

`PHP Fatal error:  Uncaught mysqli_sql_exception: Field 'description' doesn't have a default value in /home/ubuntu/.../fengoffice/public/install/installation/acInstallation.class.php:349\nStack trace:\n#0 /home/ubuntu/.../fengoffice/public/install/installation/acInstallation.class.php(349): mysqli_query()\n#1 /home/ubuntu/.../fengoffice/public/install/installation/acInstallation.class.php(714): acInstallation->executeMultipleQueries()\n#2 /home/ubuntu/.../fengoffice/public/install/installation/acInstallation.class.php(218): acInstallation->installPlugins()\n#3 /home/ubuntu/.../fengoffice/public/install/installation/steps/FinishStep.class.php(56): acInstallation->execute()\n#4 /home/ubuntu/.../fengoffice/public/install/library/classes/ScriptInstaller.class.php(93): FinishStep->execute()\n#5 /home/ubuntu/.../fengoffice/public/install/index.php(11): ScriptInstaller->executeStep()\n#6 {main}\n  thrown in /home/ubuntu/.../fengoffice/public/install/installation/acInstallation.class.php on line 349, referer: https://.../fengoffice/public/install/index.php?step=3`

Can I help in any other way?

**Comment by sgrimmett** [comment]
@savchenkolex Did you get a fix for this?  I'm having troubles with upgrading from version 3.8.5.35 and tried to do a fresh install - same error you are receiving on step 4.  The only difference for me is php 8.1 vs php 7.4

Installer builds config file, then begins to import initial data.  Then Plugins aren't installed.    I believe it's the plugins that are failing, but haven't yet had the time to go down the rabbit hole on this.

**Comment by sgrimmett** [comment]
@SantiFeng Thank you.  I'll try to dig into this a bit more as I have time as well.  Cannot do upgrade from 3.8.5.35 to 3.10.8.6, not sure if it is recommended or required to follow a 3.8.x - 3.9.x -> 3.10.x?  Perhaps I will try that as I've fallen behind on upgrading, waiting for full php8 compatibility.

**Comment by sgrimmett** [comment]
@SantiFeng In an attempt to follow an upgrade path using our legacy php7 server from 3.8.5.35 to 3.8.6.13 - we are first trialing a clean install - and, we get this error.  Therefore, the "description" issue is related to core_dimensions plugin.

Found faulty query: INSERT INTO `fo_members` (`dimension_id`,`object_type_id`, `parent_member_id`, `depth`, `name`, `object_id` ) SELECT (SELECT `id` FROM `fo_dimensions` WHERE `code`='feng_persons'), (SELECT `id` FROM `fo_object_types` WHERE `name`='company'), 0, 1, `o`.`name`, `o`.`id` FROM `fo_objects` `o` INNER JOIN `fo_contacts` `c` ON `c`.`object_id`=`o`.`id` WHERE `c`.`is_company`=1 ON DUPLICATE KEY UPDATE dimension_id=dimension_id
Error while loading inital data for plugin 'core_dimensions'. Field 'description' doesn't have a default value

However, on upgrade from 3.8.5.35 to 3.8.6.13 - all appears to work fine on php7.  Will continue testing, and then progress further up the version chain...  there is no 3.9 versions - just a jump from 3.8.6.13 to 3.10.x - will try on php7.4 first so that there are no server changes, then will examine php8.1

**Comment by sgrimmett** [comment]
To followup - upgrading to 3.10.8.6 on php7.3 works fine and throws no errors.  Next attempt will be moving to our new php8.1 server...  but, I wonder if php 8.1 is supported?  Or, just php 8.0?  Anyone know the clear answer on this?
