### ISSUE TITLE
php8.1

### ISSUE THREAD

**Issue by sgrimmett** [fengoffice/fengoffice#97]
So - 3.10.8.6 mostly works on php8.1, but runs into a few issues... all related to : 

Call to undefined function mysqli_connect() in /environment/library/database/adapters/MysqliDBAdapter.class.php:28

The calls come from the following files:

/html/application/helpers/save_user_permissions.php(5): include('...')
/application/helpers/save_member_permissions.php(5): include('...')
/plugins/mail/application/helpers/send_outbox_emails.php(5): include('...')
/application/helpers/add_object_to_sharing_table.php(5): include('...')

So, emails cue up in outbox, and no member permissions can be updated.

Other issues coming up in logs that don't seem to impact function include:

#1 ERROR: Error: Trying to access array offset on value of type null in '/application/controllers/ObjectController.class.php' on line 870 (error code: 2)
#2 ERROR: Error: Trying to access array offset on value of type null in 'application/controllers/ObjectController.class.php' on line 883 (error code: 2)

All in all - does not yet seem php8.1 ready, reverting to php 7.3 that works, and will continue to hope for additional php8 support!

**Comment by sgrimmett** [comment]
So, trialing 3.10.8.21 on php8.1 and still errors..  So, we're runing our server mainly on php7.3 that is working well.  We would like to be able to upgrade to php8.1 however.  Should we be working with php8.0 instead?  

Here's another one:  on emply trash, nothing happens, and page goes blank with the following error.

#1 FATAL: Error: Non-static method ContentDataObjects::listing() cannot be called statically in /application/controllers/ObjectController.class.php:2186
    Stack trace:
    #0/application/controllers/ObjectController.class.php(2430): ObjectController->processListActions()
    #1 /application/controllers/ObjectController.class.php(2296): ObjectController->get_objects_list()
    #2 /environment/classes/controller/Controller.class.php(76): ObjectController->list_objects()
    #3 /environment/classes/controller/PageController.class.php(62): Controller->execute()
    #4 /environment/classes/Env.class.php(133): PageController->execute()
    #5 /init.php(179): Env::executeAction()
    #6 /index.php(7): require('...')
    #7 {main}
Time since start: 0.030009984970093 seconds
-------------------------------------------------------------------------------

**Comment by sgrimmett** [comment]
3.11.1.2 is getting better with php8.1, but this issue contines to exist on empty trash.

**Comment by sgrimmett** [comment]
@alvarotm01 This issue remains in 3.11.8.0 - same error - line numbers updated below:

#1 FATAL: Error: Non-static method ContentDataObjects::listing() cannot be called statically in /html/application/controllers/ObjectController.class.php:2229
    Stack trace:
    #0 /application/controllers/ObjectController.class.php(2480): ObjectController->processListActions()
    #1application/controllers/ObjectController.class.php(2346): ObjectController->get_objects_list()
    #2 /environment/classes/controller/Controller.class.php(76): ObjectController->list_objects()
    #3 /environment/classes/controller/PageController.class.php(62): Controller->execute()
    #4 /environment/classes/Env.class.php(133): PageController->execute()
    #5 /init.php(178): Env::executeAction()
    #6 /index.php(7): require('...')
    #7 {main}

**Comment by nico-lois** [comment]
Hello again! Yes we are constantly adding changes to more compatible We plan for 3.12 version only run on php8 so this is much apritiated

**Comment by sgrimmett** [comment]
Bug still exists in 3.12 beta 3.
